<?php

namespace Tests\Unit\Models;

use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use App\Models\Size;

class SizeTest extends TestCase
{
    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_user_relation()
    {
        $size = new Size();
        $relation = $size->products();
        $this->assertInstanceOf(BelongsToMany::class, $relation);
        $this->assertEquals('product_size.size_id', $relation->getQualifiedForeignPivotKeyName());
        $this->assertEquals('product_size.product_id', $relation->getQualifiedRelatedPivotKeyName());
    }

    public function test_table_name()
    {
        $size = new Size();
        $relation = $size->products();
        $this->assertEquals('product_size', $relation->getTable());
    }
}
