<?php

namespace Tests\Unit\Controller;

use App\Http\Controllers\CategoryController;
use App\Models\Category;
use App\Models\Product;
use App\Repositories\Category\CategoryRepositoryInterface;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Collection;
use Mockery;
use Tests\TestCase;

class CategoryTest extends TestCase
{
    protected $categoryMock;

    public function setUp(): void
    {
        $this->categoryMock = Mockery::mock(CategoryRepositoryInterface::class . '[getProduct]');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown(): void
    {
        unset($this->controller);
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_show_function()
    {
        $this->categoryMock->shouldReceive('getProduct')
            ->with(config('unit_test.category_id'), ['categories', 'products'])
            ->once()
            ->andReturn(new Category);

        $category = new CategoryController($this->categoryMock);
        $result = $category->show(config('unit_test.category_id'));
        $data = $result->getData();

        $this->assertIsArray($data);
        $this->assertEquals('products.product', $result->getName());
        $this->assertArrayHasKey('products', $data);
    }

    public function test_show_function_exception()
    {
        $this->categoryMock->shouldReceive('getProduct')
            ->with(config('unit_test.category_id'), ['categories', 'products'])
            ->once()
            ->andReturn(false);

        $category = new CategoryController($this->categoryMock);
        $result = $category->show(config('unit_test.category_id'));
        $this->assertTrue($result->isRedirect());
    }
}
